version: '3.8'

services:
  deepwiki:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMPORT_HOST_CERTS: ${IMPORT_HOST_CERTS:-false}
    ports:
      - "${PORT:-8001}:${PORT:-8001}"  # API port
      - "3000:3000"  # Next.js port
    env_file:
      - .env
    environment:
      - PORT=${PORT:-8001}
      - NODE_ENV=production
      - SERVER_BASE_URL=http://localhost:${PORT:-8001}
      - NEXT_PUBLIC_SERVER_BASE_URL=http://localhost:${PORT:-8001}
    volumes:
      - ~/.adalflow:/root/.adalflow  # Persist repository and embedding data
      # Optional: mount host CA certificates to include custom trust roots
      # - ./certs:/etc/ssl/certs:ro
    # Resource limits for docker-compose up (not Swarm mode)
    mem_limit: 6g
    mem_reservation: 2g
    # Health check configuration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8001}/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
